// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJjCdWNjRaz5svGYh1ipca4FZ9S2jBGFo',
    appId: '1:447315523174:web:0faec17272a29c9e049fa7',
    messagingSenderId: '447315523174',
    projectId: 'tracker-5a23e',
    authDomain: 'tracker-5a23e.firebaseapp.com',
    storageBucket: 'tracker-5a23e.firebasestorage.app',
    measurementId: 'G-0G8C03VZZN',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwsjh6SlKMLYlWjzm9hdP9pin90s2aOUo',
    appId: '1:447315523174:ios:ab26e39104441fd6049fa7',
    messagingSenderId: '447315523174',
    projectId: 'tracker-5a23e',
    storageBucket: 'tracker-5a23e.firebasestorage.app',
    iosBundleId: 'com.example.petTrack',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmSuQAbF1gMsIWVS8YilTYqm8PgJuMY7s',
    appId: '1:447315523174:android:f8cc1cf5a24c90b5049fa7',
    messagingSenderId: '447315523174',
    projectId: 'tracker-5a23e',
    storageBucket: 'tracker-5a23e.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArcOSgCmhewyuCsgHNyFok4sdEWH2JeIA',
    appId: '1:749247598865:ios:efc20be6a311c05e943cb0',
    messagingSenderId: '749247598865',
    projectId: 'temp-2b758',
    storageBucket: 'temp-2b758.firebasestorage.app',
    iosBundleId: 'com.petapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTSFSQOQQlU-h8AxE2Gj8vuHduFfga0hs',
    appId: '1:749247598865:web:2723e42ccb651005943cb0',
    messagingSenderId: '749247598865',
    projectId: 'temp-2b758',
    authDomain: 'temp-2b758.firebaseapp.com',
    storageBucket: 'temp-2b758.firebasestorage.app',
  );

}